/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UnauthenticatedIndexImport } from './routes/unauthenticated/index'
import { Route as HelpIndexImport } from './routes/help/index'
import { Route as AuthenticatedIndexImport } from './routes/authenticated/index'
import { Route as AuthenticatedHomeIndexImport } from './routes/authenticated/home/index'

// Create/Update Routes

const UnauthenticatedIndexRoute = UnauthenticatedIndexImport.update({
  path: '/unauthenticated/',
  getParentRoute: () => rootRoute,
} as any)

const HelpIndexRoute = HelpIndexImport.update({
  path: '/help/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  path: '/authenticated/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedHomeIndexRoute = AuthenticatedHomeIndexImport.update({
  path: '/authenticated/home/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/authenticated/': {
      id: '/authenticated/'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof rootRoute
    }
    '/help/': {
      id: '/help/'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpIndexImport
      parentRoute: typeof rootRoute
    }
    '/unauthenticated/': {
      id: '/unauthenticated/'
      path: '/unauthenticated'
      fullPath: '/unauthenticated'
      preLoaderRoute: typeof UnauthenticatedIndexImport
      parentRoute: typeof rootRoute
    }
    '/authenticated/home/': {
      id: '/authenticated/home/'
      path: '/authenticated/home'
      fullPath: '/authenticated/home'
      preLoaderRoute: typeof AuthenticatedHomeIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthenticatedIndexRoute,
  HelpIndexRoute,
  UnauthenticatedIndexRoute,
  AuthenticatedHomeIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/authenticated/",
        "/help/",
        "/unauthenticated/",
        "/authenticated/home/"
      ]
    },
    "/authenticated/": {
      "filePath": "authenticated/index.tsx"
    },
    "/help/": {
      "filePath": "help/index.tsx"
    },
    "/unauthenticated/": {
      "filePath": "unauthenticated/index.tsx"
    },
    "/authenticated/home/": {
      "filePath": "authenticated/home/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
